---
title: "2019 KHPC Analytics"
author: "Cornelius Tanui"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    vertical_layout: scroll
    # source_code: embed
    logo: logo.jpg
    theme: lumen
date: "`r Sys.Date()`"
runtime: shiny
---

<!--
# Customizing HTML Appearance
-->

<style>
.navbar {
background-color:#438D80;
border-color: #15317E;
}

.navbar-brand {
color: #000000! important;
}

.section.sidebar {
background-color:#438D80;
border-color: #15317E;
color: #000000! important;
}

</style>

```{r Clear Evrironment, include = FALSE}
gc()
graphics.off()
rm(list = ls(all.names = TRUE))
```

```{r Load Packages, include = FALSE}
# load Packages
library(kableExtra)
library(MASS)
library(Matrix)
library(lattice)
library(mgcv)
library(nlme)
library(tidyverse)
library(flexdashboard)
library(shiny)
library(plotly)
library(DT)
library(ggplot2)
library(ggpmisc)
library(gmodels)
library(magrittr)
library(rKenyaCensus)
```

Home
==================================================
Row {.tabset .tabset-fade}
--------------------------------------------------
### Introduction

This secondary data from Kenya Household and Population Census ([KPHC](https://www.knbs.or.ke/)) of 2019, made available in R by [Shelmith Kariuki](https://shelkariuki.netlify.app/#about) through her elegantly written [`rKenyaCensus`](https://github.com/Shelmith-Kariuki/rKenyaCensus) package. 

This Shiny application uses [`flexdashboard`](https://rstudio.github.io/flexdashboard/index.html) framework. 

### Data 

Data files avaliable for public use; 

```{r}
data_description<- rKenyaCensus::DataCatalogue %>% 
  as.data.frame()

data_description %>% 
  kbl() %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>% 
  scroll_box(width = "100%", height = "400px")

```

Dashboards
==================================================
Row {.tabset .tabset-fade}
--------------------------------------------------

### Demographics

```{r}

```

### Health

```{r}

```